# Define project name, FPU, Heap & Stack here
# PROJECT		   = IO_Toggle

# Derive the project name from the current folder.
PROJECT        = $(notdir $(CURDIR))

SRC+=./stm32f4xx_lp_modes.c
include ../Common.mk