# Project Name (If blank the folder name is used as project name)
PROJECT= 
# List the user directory to look for the libraries here
ULIBDIR=
# List all user libraries here
ULIBS  = 
# Define ASM defines here
UADEFS = 
# Define C defines here
UCDEFS = 

include ../Common.mk