# Define project name, FPU, Heap & Stack here
# PROJECT		   = IO_Toggle

# Derive the project name from the current folder.
PROJECT        = $(notdir $(CURDIR))

# LIS302DLMEMS motion sensor 3-axis ±2g/±8g smart digital output accelerometer
SRC+=$(DISCOVERY)/stm32f4_discovery_lis302dl.c

include ../Common.mk